# springboot related config file

logging:
  level:
    com: INFO

server:
    port: 8090

credentials:
  project-id:
  key-id:
  key-secret:

# Set a value if not using the default "us" region
sms:
  region:
