# springboot related config file

logging:
  level:
    com: INFO

server:
  port: 8090

credentials:
  # Unified related credentials, used by:
  # - Numbers
  # - SMS
  project-id:
  key-id:
  key-secret:

  # Application related credentials, used by:
  # - Verification
  # - Voice
  application-api-key:
  application-api-secret: 

sms:
  # Sets the region for SMS
  # valid values are US and EU
  region:

# Secret value set for Numbers webhooks calls validation
numbers.webhooks.secret:
