# springboot related config file

logging:
  level:
    com: INFO

server:
    port: 8080

credentials:
  # Unified related credentials, used by:
  # - Numbers
  # - SMS
  project-id:
  key-id:
  key-secret:

  # Application related credentials, used by:
  # - Verification
  # - Voice
  application-api-key:
  application-api-secret: 
