# springboot related config file

logging:
  level:
    com: INFO

server:
  port: 8090

credentials:
  # Unified related credentials, used by:
  # - Numbers
  # - SMS
  project-id:
  key-id:
  key-secret:
