# springboot related config file

logging:
  level:
    com: INFO

server:
  port: 8090

credentials:
  project-id:
  # Required credentials for using the SMS API
  # US/EU are the only supported regions with unified credentials
  key-id:
  key-secret:

sms:
  # Sets the region for SMS
  # valid values are US and EU
  region:

sms.webhooks.secret:
  