# springboot related config file

logging:
  level:
    com: INFO

server:
  port: 8090

credentials:
  # Application related credentials, used by:
  # - Verification
  # - Voice
  application-api-key:
  application-api-secret:
