# springboot related config file

logging:
  level:
    com: INFO

server:
    port: 8090

credentials:
  application-api-key:
  application-api-secret: 
sinch_number: YOUR_sinch_number
sip_address: YOUR_sip_address
