# springboot related config file

logging:
  level:
    com: INFO

server:
    port: 8090

credentials:
  application-api-key:
  application-api-secret: 
sinch-number: YOUR_sinch_number
sip-address: YOUR_sip_address
